### ISSUE TITLE
Enable auto-renew on a given cert

### ISSUE THREAD

**Issue by 0xdade** [ajacques/CertManager#77]
I'm lazy and shouldn't be required to manually renew my cert before it expires.

**Comment by ajacques** [comment]
21fe855b7b7eec54eefbb067e1f91740f5e0b82c should somewhat implement this feature. Need further planning and direction

**Comment by ajacques** [comment]
I've fully enabled this feature as part of 2b8a86a27486b0ea8f9e06b8ecc4fa11b0ff844e which has now rolled out to production. Your website was the first to take advantage of this feature and has been renewed automatically.

The only remaining thing may be to properly send SIGHUP to the NGINX container as required.
